---
- name: "Run powershell scripts"
  hosts: windows
  tasks:
    - name: Install PSWindowsUpdate
      ansible.windows.win_powershell:
        script: |
         New-Item -Path "c:\" -name "testfoldercreation" -ItemType "directory"
